import type { Metadata } from "next";
import "@/styles/globals.css";
import { ThemeProvider } from "@/provider/theme-provider";
import { inter } from "@/utils/fonts";

export const metadata: Metadata = {
  title: "QRCodium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
